#!/bin/bash
#
# This hook will update the version number in the constants.dart file
# based on the version number in the pubspec.yaml file.

# Get version number
version=$(cat pubspec.yaml | grep -o -P '(?<=version: ).*(?= # Current version)')

# Replace version in constants.dart with the version number
sed -i "s/currentVersion = \".*\";/currentVersion = \"$version\";/g" lib/components/constants.dart

# Add the changes to the commit
git add lib/components/constants.dart